# Generated by Django 4.2 on 2023-04-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewsetapp', '0002_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
